application: raindrop-01
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /(.*\.js)
  static_files: assets/\1
  upload: assets/(.*\.js)

- url: /.*
  script: main.py
