"""Subclass of CustomFrame_list, which is generated by wxFormBuilder."""

import wx
import forms

# Implementing CustomFrame_list
class ScriptDownloaderCustomFrame_list( forms.CustomFrame_list ):
	def __init__( self, parent ):
		forms.CustomFrame_list.__init__( self, parent )
	
	# Handlers for CustomFrame_list events.
	def menu_close_selection( self, event ):
		# TODO: Implement menu_close_selection
		pass
	
	def menu_refresh_selection( self, event ):
		# TODO: Implement menu_refresh_selection
		pass
	
	def m_tool_prev_click( self, event ):
		# TODO: Implement m_tool_prev_click
		pass
	
	def m_tool_next_click( self, event ):
		# TODO: Implement m_tool_next_click
		pass
	
	def m_tool_refresh_click( self, event ):
		# TODO: Implement m_tool_refresh_click
		pass
	
	def m_tool_home_click( self, event ):
		# TODO: Implement m_tool_home_click
		pass
	
	
