"""Subclass of CustomFrame_detail, which is generated by wxFormBuilder."""

import wx
import forms

# Implementing CustomFrame_detail
class ScriptDownloaderCustomFrame_detail( forms.CustomFrame_detail ):
	def __init__( self, parent ):
		forms.CustomFrame_detail.__init__( self, parent )
	
	# Handlers for CustomFrame_detail events.
	def m_button_install_click( self, event ):
		# TODO: Implement m_button_install_click
		pass
	
	def m_button_close_click( self, event ):
		# TODO: Implement m_button_close_click
		pass
	
	
